name: Deploy to Cloud Run

on:
  workflow_dispatch:
    inputs:
      NEW_ENV_VAR:
        description: 'New environment variable value'
        required: true
      GCP_PROJECT:
        description: 'Google Cloud Project ID'
        required: true
      CLOUD_RUN_SERVICE:
        description: 'Cloud Run Service Name'
        required: true
      IMAGE_NAME:
        description: 'Container Image to Deploy'
        required: true
      SECRET_NAME:
        description: 'Secret Name in Secret Manager'
        required: true
      ENV_VAR_NAME:
        description: 'Environment Variable Name in Cloud Run Service'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate to Google Cloud
      run: gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}

    - name: Configure gcloud project
      run: gcloud config set project ${{ github.event.inputs.GCP_PROJECT }}

    - name: Add environment variable to Secret Manager
      run: |
        echo "${{ github.event.inputs.NEW_ENV_VAR }}" | gcloud secrets create ${{ github.event.inputs.SECRET_NAME }} --data-file=-

    - name: Grant Secret Manager Access to Cloud Run
      run: |
        PROJECT_NUMBER=$(gcloud projects describe ${{ github.event.inputs.GCP_PROJECT }} --format="value(projectNumber)")
        gcloud secrets add-iam-policy-binding ${{ github.event.inputs.SECRET_NAME }} \
          --member=serviceAccount:${PROJECT_NUMBER}-compute@developer.gserviceaccount.com \
          --role='roles/secretmanager.secretAccessor'

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ github.event.inputs.CLOUD_RUN_SERVICE }} \
          --image gcr.io/${{ github.event.inputs.GCP_PROJECT }}/${{ github.event.inputs.IMAGE_NAME }} \
          --update-env-vars=${{ github.event.inputs.ENV_VAR_NAME }}=projects/${{ github.event.inputs.GCP_PROJECT }}/secrets/${{ github.event.inputs.SECRET_NAME }}/versions/latest
