name: Deploy to Private Server via IAP

on:
  push:
    branches:
      - main
      - development
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (prod/dev)'
        required: true
        default: dev

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: seva-ffbb6

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Clean up package cache
      #   run: |
      #     sudo apt-get clean
      #     sudo apt-get autoremove -y
      #     sudo apt-get update

      # - name: Fix broken dependencies
      #   run: |
      #     sudo apt-get install -f

      # - name: Remove conflicting packages
      #   run: |
      #     sudo apt-get remove -y containerd.io containerd

      # - name: Set up Google Cloud SDK with Workload Identity
      #   uses: google-github-actions/auth@v1
      #   with:
      #     workload_identity_provider: 'projects/497015003686/locations/global/workloadIdentityPools/github-action-pool/providers/github-actions-provider'
      #     service_account: 'github-actions@seva-ffbb6.iam.gserviceaccount.com'

      - name: Set Environment Variables
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            ENV="${{ github.event.inputs.environment }}"
          else
            if [ "${{ github.ref }}" == "refs/heads/main" ]; then
              ENV="prod"
            elif [ "${{ github.ref }}" == "refs/heads/development" ]; then
              ENV="dev"
            else
              echo "Unknown branch. Exiting."
              exit 1
            fi
          fi
          echo "ENV=$ENV" >> $GITHUB_ENV
          if [ "$ENV" == "prod" ]; then
            echo "VM_NAME=us-west1-prod-external-services" >> $GITHUB_ENV
          else
            echo "VM_NAME=us-west1-dev-external-services" >> $GITHUB_ENV
          fi
      - name: Log Environment
        run: echo "Deploying $ENV on branch ${{ github.ref }}"
        
      - name: Deploy via IAP
        run: |
            echo "Deploying on $VM_NAME"
          # gcloud compute ssh $VM_NAME \
          #   --tunnel-through-iap \
          #   --zone=us-west1-b \
          #   --project=$PROJECT_ID \
          #   --command="sudo su && cd /home/runner && ./deploy.sh"
